services:
  db:
    image: mysql
    container_name: ${PROJECT_NAME}-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: zsf
      MYSQL_ROOT_PASSWORD: P@55word
    volumes:
      - ./init-scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql