services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: ${PROJECT_NAME}-web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html

  adminer:
    image: adminer
    container_name: ${PROJECT_NAME}-adminer
    depends_on:
      - db
    ports:
      - "8081:8080"