services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-20.04
    container_name: ${PROJECT_NAME}-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: P@55word
      ACCEPT_EULA: "Y"
    volumes:
      - ./init-scripts/sqlsrv-init.sql:/docker-entrypoint-initdb.d/sqlsrv-init.sql