ARG NODE_VERSION=22.5.1

FROM node:${NODE_VERSION}

ENV NODE_ENV=development
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV HOST=0.0.0.0

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN chown -R node:node /app/node_modules

EXPOSE 5173

USER node

CMD ["/bin/sh", "-c", "pnpm install; pnpm dev"]