ARG NODE_VERSION=22.5.1
ARG NODE_PORT=5173

FROM node:${NODE_VERSION}-alpine AS base

ENV NODE_ENV=development
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

COPY . /app

RUN corepack enable

EXPOSE ${NODE_PORT}

CMD ["/bin/sh", "-c", "pnpm install; pnpm dev"]