services:
  db:
    image: postgres
    container_name: ${PROJECT_NAME}-db
    environment:
      POSTGRES_PASSWORD: P@55word
      POSTGRES_DB: zsf
    volumes:
      - ./init-scripts/pgsql-init.sql:/docker-entrypoint-initdb.d/pgsql-init.sql