services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: ${PROJECT_NAME}-web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html

  adminer:
    image: adminer
    container_name: ${PROJECT_NAME}-adminer
    depends_on:
      - db
    ports:
      - "8081:8080"

  db:
    image: mysql
    container_name: ${PROJECT_NAME}-db
    environment:
      MYSQL_DATABASE: zsf
      MYSQL_ROOT_PASSWORD: P@55word

  front:
    build:
      context: ../ui/front
      dockerfile: ../../docker/Dockerfile-node
    container_name: ${PROJECT_NAME}-front
    depends_on:
      - web
    ports:
      - "5173:5173"
    volumes:
      - ../ui/front:/app
      - ../ui/front/src:/app/src