services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-20.04
    container_name: ${PROJECT_NAME}-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: P@55word
      ACCEPT_EULA: "Y"
    volumes:
      - ./init-scripts/sqlsrv-init.sql:/docker-entrypoint-initdb.d/sqlsrv-init.sql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@55word' -Q 'SELECT 1'" ]
      interval: 15s
      timeout: 5s
      retries: 5